### ISSUE TITLE
New author page should save the author

### ISSUE THREAD

**Issue by swt2public** [Baschdl/rails-exercise-16#13]
When a user visits the new author page
And fills in 'Alan', 'Turing', and 'http://wikipedia.org/Alan_Turing', respectively
And submits the form
Then Alan Turing should be found in the database

Got ActiveRecord::RecordNotFound: Couldn't find Author

**Comment by derari** [comment]
In `app/views/authors/new.html.erb` Zeile 2:

> ```
> <%= form_for :authors, url: authors_path do |f| %>
> ```

sollte 

> ```
> <%= form_for :author, url: authors_path do |f| %>
> ```

sein. Das sollte es hoffentlich fixen.

Ich nehme mal zur Kenntnis dass die Fehlermeldung an der Stelle nicht hilfreich ist und werde mal schauen wie ich das verbessern kann.

**Comment by Baschdl** [comment]
@derari Vielen Dank, ich habe gemerkt, dass ich das auf dem anderen Branch anscheinend mal korrigiert habe. Bei #16 ist die Fehlermeldung auch nicht sehr aussagekräftig, vor allem da es ein wiederkehrendes Issue vom Anfang ist (Ich habe die möglichen Klein- und Großschreibungen ausprobiert).
